version: '2.1'

services:
  php:
    image: php:7-apache
    container_name: lemp_php7_apache
    restart: always
    volumes:
      - ./web/:/var/www/html
    ports:
      - 80:80
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=animaldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root